-- Project Automation Engine (project-scoped WHEN/IF/THEN rules).
-- Four schema changes: rules table, per-(rule,action) RR cursors, audit runs
-- log (incl. skips), cards provenance columns + bounce-guard unique index.
CREATE TABLE IF NOT EXISTS "project_automation_rules" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "organization_id" uuid NOT NULL, "project_id" uuid NOT NULL, "name" varchar(200) NOT NULL, "is_enabled" boolean NOT NULL DEFAULT true, "schema_version" integer NOT NULL DEFAULT 1, "trigger_json" jsonb NOT NULL, "condition_json" jsonb NOT NULL DEFAULT '{}', "action_json" jsonb NOT NULL DEFAULT '[]', "needs_attention" boolean NOT NULL DEFAULT false, "attention_reason" text, "last_executed_at" timestamp, "execution_count" integer NOT NULL DEFAULT 0, "created_by" uuid, "created_at" timestamp NOT NULL DEFAULT now(), "updated_at" timestamp NOT NULL DEFAULT now(), "deleted_at" timestamp, CONSTRAINT "project_automation_rules_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "project_automation_rules_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "project_automation_rules_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "project_auto_rules_org_idx" ON "project_automation_rules" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "project_auto_rules_project_idx" ON "project_automation_rules" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "project_auto_rules_enabled_idx" ON "project_automation_rules" USING btree ("project_id") WHERE is_enabled = true;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "automation_rule_cursors" ("rule_id" uuid NOT NULL, "action_id" uuid NOT NULL, "position" integer NOT NULL DEFAULT 0, "last_user_id" uuid, "updated_at" timestamp NOT NULL DEFAULT now(), CONSTRAINT "automation_rule_cursors_rule_id_action_id_pk" PRIMARY KEY("rule_id","action_id"), CONSTRAINT "automation_rule_cursors_rule_id_project_automation_rules_id_fk" FOREIGN KEY ("rule_id") REFERENCES "project_automation_rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "automation_rule_cursors_last_user_id_users_id_fk" FOREIGN KEY ("last_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "automation_rule_runs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "rule_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "project_id" uuid NOT NULL, "card_id" uuid, "event_id" varchar(100), "status" varchar(16) NOT NULL DEFAULT 'executed', "reason" varchar(32), "details" jsonb NOT NULL DEFAULT '{}', "created_at" timestamp NOT NULL DEFAULT now(), CONSTRAINT "automation_rule_runs_rule_id_project_automation_rules_id_fk" FOREIGN KEY ("rule_id") REFERENCES "project_automation_rules"("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "automation_rule_runs_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "automation_rule_runs_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "automation_rule_runs_card_id_cards_id_fk" FOREIGN KEY ("card_id") REFERENCES "cards"("id") ON DELETE SET NULL ON UPDATE NO ACTION);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "auto_runs_rule_created_idx" ON "automation_rule_runs" USING btree ("rule_id","created_at" DESC);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "auto_runs_project_created_idx" ON "automation_rule_runs" USING btree ("project_id","created_at" DESC);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "auto_runs_rule_event_idx" ON "automation_rule_runs" USING btree ("rule_id","event_id");--> statement-breakpoint
ALTER TABLE "cards" ADD COLUMN IF NOT EXISTS "source_rule_id" uuid;--> statement-breakpoint
ALTER TABLE "cards" ADD COLUMN IF NOT EXISTS "source_action_id" uuid;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "cards_automation_bounce_idx" ON "cards" USING btree ("parent_card_id","source_rule_id","source_action_id") WHERE parent_card_id IS NOT NULL AND source_rule_id IS NOT NULL AND source_action_id IS NOT NULL AND is_archived = false AND deleted_at IS NULL;
